jobs:
  - name: copy-rnd
    plan:
      - get: rnd-repo
        trigger: true
      - get: impact-measures-repo
        trigger: true
      - get: chs-how-many-repo
        trigger: true
      - get: chs-auditlog-repo
        trigger: true
      - get: chs-uc-lab-repo
        trigger: true
#      - get: datateam_dotfiles-repo
#        trigger: true
      - task: copy-rnd-repo
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_python_boto_behave_repository))
              version: 0.0.24
              tag: 0.0.24
          params:
            AWS_ACC: ((dataworks.aws_dev_acc))
            AWS_REGION: ((dataworks.aws_region))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
          run:
            path: sh
            args:
              - -exc
              - |
                source /assume-role
                export REPO=Data_Science-production
                apk add git
                pip install git-remote-codecommit
                git config --global user.email ""
                git config --global user.name "Mirror Job"
                git clone codecommit::eu-west-2://${REPO} /root/${REPO}
                for i in $(ls ./); do
                  name=$(echo $i | sed s/-repo//g)
                  rm -Rf /root/${REPO}/mirrors/${name}
                  mkdir -p /root/${REPO}/mirrors/${name}
                  cp -Rfp ./${i}/* /root/${REPO}/mirrors/${name}/
                  ls ./${i}/
                  ls /root/${REPO}/mirrors/${name}/
                  ls /root/${REPO}/mirrors/
                  rm -Rf /root/${REPO}/mirrors/${name}/.git
                done
                cd /root/${REPO}
                echo $(git status --porcelain)
                if [[ ! -z "$(git status --porcelain)" ]]; then
                  git add -A
                  git commit -m"Mirroring"
                  git push
                fi
                UNTRACKED=$(git status -s | wc -l)
                test $UNTRACKED -eq 0
          inputs:
            - name: rnd-repo
            - name: impact-measures-repo
            - name: chs-how-many-repo
            - name: chs-auditlog-repo
            - name: chs-uc-lab-repo
#            - name: datateam_dotfiles-repo

  - name: copy-rnd-incoming
    plan:
      - get: working-day-copy-trigger
        trigger: true
      - get: rnd-incoming-repo
        trigger: false
      - task: copy-into-rnd-repo
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_python_boto_behave_repository))
              version: 0.0.24
              tag: 0.0.24
          params:
            AWS_ACC: ((dataworks.aws_dev_acc))
            AWS_REGION: ((dataworks.aws_region))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
          run:
            dir: rnd-incoming-repo
            path: sh
            args:
              - -exc
              - |
                source /assume-role
                export TARGET_DIR=$(pwd)
                export REPO=Data_Science-production
                apk add git
                pip install git-remote-codecommit
                git config --global user.email ""
                git config --global user.name "Mirror Job"
                git clone codecommit::eu-west-2://${REPO} /root/${REPO}
                rm -Rf /root/${REPO}/mirrors/rnd
                if [[ -d /root/${REPO}/outgoing/rnd ]]
                then
                    cp -Rfpv /root/${REPO}/outgoing/rnd/* ./
                    git add -A
                    git commit -m"Mirroring" || true
                fi
                UNTRACKED=$(git status -s | wc -l)
                test $UNTRACKED -eq 0
          inputs:
            - name: rnd-incoming-repo
          outputs:
            - name: rnd-incoming-repo
      - put: rnd-incoming-repo
        params:
          repository: rnd-incoming-repo
