jobs:
  - name: development
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-development
      - get: emp-release
        trigger: true
      - get: aws-analytical-env
        trigger: true
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: infra
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_VAR_emp_dir_path: ../../../../emp-release 
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_VAR_emp_dir_path: ../../../../emp-release
      - .: (( inject meta.plan.terraform-output-analytical-dataset-generation ))
        task: get variables for e2e
      - .: (( inject meta.plan.analytical-env-e2e-tests ))
        config:
          params:
            TF_ADG_OUTPUT_FILE: terraform-output-analytical-dataset-generation/outputs.json
