jobs:
  - name: integration
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-integration
      - get: emp-release
        version: { tag: '0.0.6' }
        passed:
          - qa
        trigger: true  
      - get: aws-analytical-env
        passed:
          - qa
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: infra
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_WORKSPACE: 'integration'
          TF_VAR_emp_dir_path: ../../../../emp-release
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_WORKSPACE: 'integration'
          TF_VAR_emp_dir_path: ../../../../emp-release  

