jobs:
  - name: after-midnight-check
    plan:
      - get: emp-release
        passed:
          - preprod
        trigger: false
      - get: emr-launcher-release
        passed:
          - preprod
        trigger: false
      - get: aws-analytical-env
        passed:
          - preprod
        trigger: false
      - get: manage-mysql-user-release
        passed:
          - preprod
        trigger: false
      - get: midnight-trigger
        trigger: true

  - name: production
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-production
      - get: emp-release
        passed:
          - preprod
          - after-midnight-check
        trigger: true
      - get: emr-launcher-release
        passed:
          - preprod
          - after-midnight-check
        trigger: true
      - get: aws-analytical-env
        passed:
          - preprod
          - after-midnight-check
        trigger: true
      - get: manage-mysql-user-release
        passed:
          - preprod
          - after-midnight-check
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: infra
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply-infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan-infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply-app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
            - name: manage-mysql-user-release
        params:
          TF_WORKSPACE: 'production'
          TF_VAR_emp_dir_path: ../../../../emp-release
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan-app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
            - name: manage-mysql-user-release
        params:
          TF_WORKSPACE: 'production'
          TF_VAR_emp_dir_path: ../../../../emp-release

