jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-qa
      - get: aws-analytical-env
        trigger: true
      - get: emp-release
        trigger: true
      - get: emr-launcher-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: infra
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan infra
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release  
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release  

