jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-qa
      - get: aws-analytical-env
        trigger: true
      - get: emp-release
        version: { tag: '0.0.6' }
        trigger: true
      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release  
      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release  

