---
Applications:
- Name: "Spark"
- Name: "Livy"
- Name: "Hive"
CustomAmiId: "${ami}"
EbsRootVolumeSize: 100
LogUri: "s3://${log_bucket}/logs/"
Name: "aws-analytical-env"
ReleaseLabel: "emr-${release_version}"
SecurityConfiguration: "${security_configuration}"
ScaleDownBehavior: "TERMINATE_AT_TASK_COMPLETION"
ServiceRole: "arn:aws:iam::${account}:role/AE_EMR_Role"
JobFlowRole: "arn:aws:iam::${account}:instance-profile/AE_EMR_EC2_Role"
VisibleToAllUsers: True
Tags:
- Key: "Name"
  Value: "batch-analytical-env"
- Key: "Application"
  Value: "${application_tag_value}"
- Key: "Environment"
  Value: "${environment_tag_value}"
- key: "Function"
  Value: "${function_tag_value}"
- key: "Business-Project"
  Value: "${business_project_tag_value}"
- Key: "DWX_Application"
  Value: "aws-analytical-env"
- Key: "DWX_Environment"
  Value: "${dwx_environment_tag_value}"
- Key: "AutoShutdown"
  Value: "False"
- Key: "Persistence"
  Value: "True"
- Key: "ProtectSensitiveData"
  Value: "True"
- Key: "SSMEnabled"
  Value: "True"
