jobs:
  - name: update-keystore-data-preprod
    max_in_flight: 1
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - update-keystore-data-integration
      - .: (( inject meta.plan.terraform-dataworks-analytical-frontend-service-bootstrap ))
      - .: (( inject meta.plan.terraform-output-frontend-service ))
        config:
          params:
            TF_WORKSPACE: preprod
      - .: (( inject meta.plan.put_keystore_data ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
