jobs:
  - name: mirror-git-repo-uc-lab-repo-development
    plan:
      - get: chs-uc-lab-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: chs-uc-lab-repo
          inputs:
            - name: chs-uc-lab-repo
          params:
            S3_ROOT: component/uc_repos/chs-uc-lab/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: mirror-git-repo-opsmi-ops-mi-repo-development
    plan:
      - get: opsmi-chs-ops-mi-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: opsmi-chs-ops-mi-repo
          inputs:
            - name: opsmi-chs-ops-mi-repo
          params:
            S3_ROOT: component/uc_repos/opsmi-chs-ops-mi-repo/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: mirror-git-repo-chs-payment-timelines-development
    plan:
      - get: chs-payment-timelines-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: chs-payment-timelines-repo
          inputs:
            - name: chs-payment-timelines-repo
          params:
            S3_ROOT: component/uc_repos/chs-payment-timelines/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: mirror-git-repo-chs-cbol-data-development
    plan:
      - get: chs-cbol-data-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: chs-cbol-data-repo
          inputs:
            - name: chs-cbol-data-repo
          params:
            S3_ROOT: component/uc_repos/chs-cbol-data/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
