jobs:
  - name: mirror-git-repo-uc-lab-repo-integration
    plan:
      - get: aws-uc-lab-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-uc-lab-repo
          inputs:
            - name: aws-uc-lab-repo
          params:
            S3_ROOT: component/uc_repos/aws-uc-lab/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-opsmi-ops-mi-repo-integration
    plan:
      - get: opsmi-chs-ops-mi-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: opsmi-chs-ops-mi-repo
          inputs:
            - name: opsmi-chs-ops-mi-repo
          params:
            S3_ROOT: component/uc_repos/opsmi-chs-ops-mi-repo/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-payment-timelines-integration
    plan:
      - get: aws-payment-timelines-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-payment-timelines-repo
          inputs:
            - name: aws-payment-timelines-repo
          params:
            S3_ROOT: component/uc_repos/aws-payment-timelines/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-cbol-data-integration
    plan:
      - get: aws-cbol-data-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-cbol-data-repo
          inputs:
            - name: aws-cbol-data-repo
          params:
            S3_ROOT: component/uc_repos/aws-cbol-data/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-user-data-migration-integration
    plan:
      - get: aws-user-data-migration-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-user-data-migration-repo
          inputs:
            - name: aws-user-data-migration-repo
          params:
            S3_ROOT: component/uc_repos/aws-user-data-migration/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-claimant-history-integration
    plan:
      - get: aws-claimant-history-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-claimant-history-repo
          inputs:
            - name: aws-claimant-history-repo
          params:
            S3_ROOT: component/uc_repos/aws-claimant-history/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-data-exploration-integration
    plan:
      - get: aws-data-exploration-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-data-exploration-repo
          inputs:
            - name: aws-data-exploration-repo
          params:
            S3_ROOT: component/uc_repos/aws-data-exploration/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-azkaban-dev-integration
    plan:
      - get: azkaban-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: azkaban-dev-repo
          inputs:
            - name: azkaban-dev-repo
          params:
            S3_ROOT: component/uc_repos/azkaban-dev/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-auditlog-integration
    plan:
      - get: aws-auditlog-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-auditlog-repo
          inputs:
            - name: aws-auditlog-repo
          params:
            S3_ROOT: component/uc_repos/aws-auditlog/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-auditlog-dev-integration
    plan:
      - get: aws-auditlog-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-auditlog-dev-repo
          inputs:
            - name: aws-auditlog-dev-repo
          params:
            S3_ROOT: component/uc_repos/dev/aws-auditlog/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-claimant-history-dev-integration
    plan:
      - get: aws-claimant-history-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-claimant-history-dev-repo
          inputs:
            - name: aws-claimant-history-dev-repo
          params:
            S3_ROOT: component/uc_repos/dev/aws-claimant-history/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-uc-channel-integration
    plan:
      - get: aws-uc-channel-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-uc-channel-repo
          inputs:
            - name: aws-uc-channel-repo
          params:
            S3_ROOT: component/uc_repos/aws-uc-channel/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-uc-channel-dev-integration
    plan:
      - get: aws-uc-channel-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-uc-channel-dev-repo
          inputs:
            - name: aws-uc-channel-dev-repo
          params:
            S3_ROOT: component/uc_repos/dev/aws-uc-channel/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-impact-measures-integration
    plan:
      - get: impact-measures-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: impact-measures-repo
          inputs:
            - name: impact-measures-repo
          params:
            S3_ROOT: component/uc_repos/impact-measures/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-impact-measures-dev-integration
    plan:
      - get: impact-measures-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: impact-measures-dev-repo
          inputs:
            - name: impact-measures-dev-repo
          params:
            S3_ROOT: component/uc_repos/dev/impact-measures/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-how-many-integration
    plan:
      - get: aws-how-many-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-how-many-repo
          inputs:
            - name: aws-how-many-repo
          params:
            S3_ROOT: component/uc_repos/aws-how-many/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-aws-how-many-dev-integration
    plan:
      - get: aws-how-many-dev-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-how-many-dev-repo
          inputs:
            - name: aws-how-many-dev-repo
          params:
            S3_ROOT: component/uc_repos/dev/aws-how-many/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
