jobs:
  - name: mirror-git-repo-uc-lab-repo-integration
    plan:
      - get: chs-uc-lab-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: chs-uc-lab-repo
          inputs:
            - name: chs-uc-lab-repo
          params:
            S3_ROOT: component/uc_repos/chs-uc-lab/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-dip-ops-mi-repo-integration
    plan:
      - get: dip-chs-ops-mi-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: dip-chs-ops-mi-repo
          inputs:
            - name: dip-chs-ops-mi-repo
          params:
            S3_ROOT: component/uc_repos/dip-chs-ops-mi/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-opsmi-ops-mi-repo-integration
    plan:
      - get: opsmi-chs-ops-mi-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: opsmi-chs-ops-mi-repo
          inputs:
            - name: opsmi-chs-ops-mi-repo
          params:
            S3_ROOT: component/uc_repos/opsmi-chs-ops-mi-repo/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: mirror-git-repo-chs-payment-timelines-integration
    plan:
      - get: chs-payment-timelines-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: chs-payment-timelines-repo
          inputs:
            - name: chs-payment-timelines-repo
          params:
            S3_ROOT: component/uc_repos/chs-payment-timelines/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
