jobs:
  - name: mirror-git-repo-uc-lab-repo-prod
    plan:
      - get: aws-uc-lab-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-uc-lab-repo
          inputs:
            - name: aws-uc-lab-repo
          params:
            S3_ROOT: component/uc_repos/aws-uc-lab/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: mirror-git-repo-opsmi-ops-mi-repo-prod
    plan:
      - get: opsmi-chs-ops-mi-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: opsmi-chs-ops-mi-repo
          inputs:
            - name: opsmi-chs-ops-mi-repo
          params:
            S3_ROOT: component/uc_repos/opsmi-chs-ops-mi-repo/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: mirror-git-repo-aws-payment-timelines-prod
    plan:
      - get: aws-payment-timelines-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-payment-timelines-repo
          inputs:
            - name: aws-payment-timelines-repo
          params:
            S3_ROOT: component/uc_repos/aws-payment-timelines/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: mirror-git-repo-aws-cbol-data-prod
    plan:
      - get: aws-cbol-data-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-cbol-data-repo
          inputs:
            - name: aws-cbol-data-repo
          params:
            S3_ROOT: component/uc_repos/aws-cbol-data/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: mirror-git-aws-user-data-migration-prod
    plan:
      - get: aws-user-data-migration-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-user-data-migration-repo
          inputs:
            - name: aws-user-data-migration-repo
          params:
            S3_ROOT: component/uc_repos/aws-user-data-migration/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: mirror-git-repo-aws-claimant-history-prod
    plan:
      - get: aws-claimant-history-repo
        trigger: true
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: production
      - .: (( inject meta.plan.mirror-git-repo ))
        config:
          run:
            dir: aws-claimant-history-repo
          inputs:
            - name: aws-claimant-history-repo
          params:
            S3_ROOT: component/uc_repos/aws-claimant-history/
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
