jobs:
  - name: testing-development
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-testing-dev
      - get: aws-analytical-env
        trigger: true
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-analytical-dataset-generation
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: testing
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
      - .: (( inject meta.plan.terraform-analytical-dataset-generation-bootstrap ))
      - .: (( inject meta.plan.terraform-output-analytical-dataset-generation ))
        task: get variables for e2e
      - .: (( inject meta.plan.analytical-env-e2e-tests ))
        config:
          params:
            TF_ADG_OUTPUT_FILE: terraform-output-analytical-dataset-generation/outputs.json
