jobs:
  - name: testing-production
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-testing-prod
      - get: aws-analytical-env
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: testing
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-common-config ))
        task: terraform-init-setup
        config:
          run:
            path: sh
            args:
              - -exc
              - |
                cp ../../../../terraform-config/terraform.tf .
                cp ../../../../terraform-config/terraform.tfvars .
                terraform workspace new production
          inputs:
            - name: aws-analytical-env
            - name: terraform-config
        params:
          TF_WORKSPACE: 'production'
          DEPLOY_PATH: testing

      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          DEPLOY_PATH: testing
          TF_WORKSPACE: 'production'
          TF_VAR_test_proxy_user: 'metrics_user11c'

      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          TF_WORKSPACE: 'production'
          TF_VAR_test_proxy_user: 'metrics_user11c'
          DEPLOY_PATH: testing
