jobs:
  - name: testing-production
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-testing-prod
      - get: aws-analytical-env
        trigger: false
      - get: emr-al2-ami
        trigger: false
      - get: dw-al2-ecs-ami
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: testing
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply-testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          DEPLOY_PATH: testing
          TF_WORKSPACE: 'production'
          TF_VAR_test_proxy_user: 'metrics_user11c'

      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan-testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          TF_WORKSPACE: 'production'
          TF_VAR_test_proxy_user: 'metrics_user11c'
          DEPLOY_PATH: testing
