jobs:
  - name: testing-qa
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-testing-qa
      - get: aws-analytical-env
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: testing
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_test_proxy_user: 'metrics_user11c'
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan testing
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/testing'
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_test_proxy_user: 'metrics_user11c'
