jobs:
  - name: preprod-stop-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: preprod-stop-waiting
    plan:
      - get: every-2h
        trigger: true
      - .: (( inject meta.plan.stop-waiting-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
