jobs:
  - name: int-stop-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
