jobs:
  - name: taint-int
    plan:
      - get: midnight-trigger
        trigger: true
      - get: aws-analytical-env
        trigger: false
      - get: emr-launcher-release
        trigger: false
      - get: manage-mysql-user-release
        trigger: false

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app

      - .: (( inject meta.plan.terraform-taint ))
        params:
          DEPLOY_PATH: app
          TF_WORKSPACE: 'integration'

      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emr-launcher-release
            - name: manage-mysql-user-release
        params:
          DEPLOY_PATH: app
          TF_WORKSPACE: 'integration'

      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emr-launcher-release
            - name: manage-mysql-user-release
        params:
          DEPLOY_PATH: app
          TF_WORKSPACE: 'integration'
