jobs:
  - name: taint-preprod
    plan:
      - put: meta
        resource: meta-development
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-taint ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-plan ))
        params:
          DEPLOY_PATH: app
