jobs:
  - name: apply-and-test-with-ami
    max_in_flight: 1
    serial_groups: [qa-applies]
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: aws-analytical-env
            trigger: true
            passed:
              - qa
          - get: emp-release
            trigger: true
            passed:
              - qa
          - get: emr-launcher-release
            trigger: true
            passed:
              - qa
          - get: manage-mysql-user-release
            trigger: true
            passed:
              - qa
          - get: hive-custom-auth-release
            trigger: true
            passed:
              - qa
          - get: emr-al2-ami
            resource: untested-al2-analytical-env-emr-ami
            trigger: true
          - get: dw-al2-ecs-ami
            resource: untested-dw-al2-ecs-ami
            trigger: true
      - .: (( inject meta.plan.check-ami-test-results ))
        input_mapping:
          untested_ami: emr-al2-ami
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          inputs:
            - name: previous_success
          params:
            AWS_ACC: ((aws_account.qa))
            DEPLOY_PATH: infra
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply-infra
        config:
          inputs:
            - name: previous_success
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
        params:
          TF_WORKSPACE: qa
          TEST_AMI_RUN: true
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan-infra
        config:
          inputs:
            - name: previous_success
          run:
            dir: 'aws-analytical-env/terraform/deploy/infra'
          params:
            TF_WORKSPACE: qa
            TEST_AMI_RUN: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          inputs:
            - name: previous_success
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-apply ))
        task: terraform-apply-app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
            - name: manage-mysql-user-release
            - name: hive-custom-auth-release
            - name: previous_success
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release
      - .: (( inject meta.plan.terraform-plan ))
        task: terraform-plan-app
        config:
          run:
            dir: 'aws-analytical-env/terraform/deploy/app'
          inputs:
            - name: emp-release
            - name: emr-launcher-release
            - name: manage-mysql-user-release
            - name: hive-custom-auth-release
            - name: previous_success
        params:
          TF_WORKSPACE: 'qa'
          TF_VAR_emp_dir_path: ../../../../emp-release
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          inputs:
            - name: previous_success
        params:
          DEPLOY_PATH: testing
      - .: (( inject meta.plan.terraform-output-testing ))
        config:
          inputs:
            - name: previous_success
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.test-emr-cluster ))
        attempts: 3
        config:
          inputs:
            - name: previous_success
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

    on_failure:
      do:
        - .: (( inject meta.plan.ami-test-results ))
          task: ami-test-result-fail
          config:
            params:
              RESULT: FAILED
        - get: emr-al2-ami-restored
          resource: emr-al2-ami
          trigger: false
        - .: (( inject meta.plan.terraform-bootstrap ))
          config:
            params:
              AWS_ACC: ((aws_account.qa))
        - .: (( inject meta.plan.terraform-apply ))
          config:
            params:
              TF_WORKSPACE: qa
          input_mapping:
            al2-emr-ami: emr-al2-ami-restored
        - .: (( inject meta.plan.terraform-plan ))
          config:
            params:
              TF_WORKSPACE: qa
          input_mapping:
            al2-emr-ami: emr-al2-ami-restored
    on_success:
      do:
        - .: (( inject meta.plan.ami-test-results ))
          task: ami-test-result-success
          config:
              params:
                RESULT: SUCCESS
