jobs:
  - name: dev-cleanup
    plan:
      - .: (( inject meta.plan.clean-security-configs ))
        task: clean-security-configs
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
