jobs:
  - name: preprod-stop-clusters
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta.plan.stop-cluster ))
        task: stop-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
